# Generated by Django 3.2.9 on 2022-02-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.CharField(max_length=20)),
                ('recipe_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minutes', models.IntegerField()),
                ('n_steps', models.IntegerField()),
                ('steps', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=500)),
                ('ingredients', models.CharField(max_length=1000)),
                ('n_ingredients', models.IntegerField()),
                ('recipe_id', models.CharField(max_length=20)),
            ],
        ),
    ]
