# Generated by Django 3.1.7 on 2022-02-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('michelinapp', '0002_auto_20220206_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredients_id',
            new_name='ingredient_id',
        ),
    ]
