# Generated by Django 3.2.9 on 2022-02-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michelinapp', '0003_auto_20220206_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='junction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
